AWSTemplateFormatVersion: '2010-09-09'
Description: creates bucket for gifs, IAM roles for Lambda and pi, and Lambda function
Parameters:
  PicamBucketName:
    Type: String
    Description: name for the bucket
  PicamRoleName:
    Type: String
    Description: prefix for the IAM role pi will use to upload files
    Default: picam-pi-ex
  PicamLambdaRoleName:
    Type: String
    Description: prefix for the IAM role Lambda will process gifs
    Default: picam-lambda-ex
  PicamLambdaName:
    Type: String
    Description: prefix for the Lambda function which will process gifs
    Default: picam-process-gifs
  #NOTE - this bucket is not created via the picam.yml template, you must create it beforehand and upload the code
  CodeBucketName:
    Type: String
    Description: name of bucket containing lambda code 
Resources:
  # PicamLambdaLogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Properties: 
  #     LogGroupName: !Sub '/aws/lambda/${PicamLambdaName}'
  #     RetentionInDays: 30
  PicamLambda:
    Type: AWS::Lambda::Function
    Properties: 
      Code: 
        S3Bucket: !Ref CodeBucketName
        S3Key: lambda/picam.zip
      Description: publishes gifs to social media
      Environment: 
        Variables:
          TZ: ET
          #NOTE - you must store the tokens in a systems manager parameter store beforehand
          #store must be in the same region as the cloud formation stack
          TWITTER_APP_KEY: '{{resolve:ssm:TWITTER_PICAM_APP_KEY:1}}'
          TWITTER_APP_SECRET: '{{resolve:ssm:TWITTER_PICAM_APP_SECRET:1}}'
          TWITTER_OAUTH_TOKEN: '{{resolve:ssm:TWITTER_PICAM_OAUTH_TOKEN:1}}'
          TWITTER_OAUTH_TOKEN_SECRET: '{{resolve:ssm:TWITTER_PICAM_OAUTH_TOKEN_SECRET:1}}'
          TWITTER_MESSAGE: '{{resolve:ssm:TWITTER_PICAM_STATUS_MESSAGE:2}}'
      FunctionName: !Sub '${PicamLambdaName}-${AWS::Region}'
      Handler: function.lambda_handler
      Role: !GetAtt 
        - PicamLambdaExecutionRole
        - Arn
      Runtime: python3.6
  PicamLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt
        - PicamLambda
        - Arn
      Action: 'lambda:InvokeFunction'
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub 'arn:aws:s3:::${PicamBucketName}'         #use sub and not ref to avoid circular dependency 
  PicamBucket: 
    DependsOn:
      - PicamLambdaInvokePermission
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True
      BucketEncryption: 
          ServerSideEncryptionConfiguration: 
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
      BucketName: !Ref PicamBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          -
            Event: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  -
                    Name: suffix
                    Value: '.gif'
            Function: !GetAtt
              - PicamLambda
              - Arn
  PicamBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PicamBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyIncorrectEncryptionHeader
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: 
              - !Join
                  - ''
                  - - !GetAtt 
                      - PicamBucket
                      - Arn
                    - '/*'
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': AES256
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action: 's3:PutObject'
            Resource: 
              - !Join
                  - ''
                  - - !GetAtt 
                      - PicamBucket
                      - Arn
                    - '/*'
            Condition:
              'Null':
                's3:x-amz-server-side-encryption': True
  PicamExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS : !Ref AWS::AccountId
            Action:
              - sts:AssumeRole
      Policies: 
        - PolicyName: !Sub '${PicamRoleName}-${AWS::Region}-permissions'
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Sid: WriteToGifsFolder
                Action: 's3:PutObject'
                Effect: Allow
                Resource: 
                  - !Sub 'arn:aws:s3:::${PicamBucketName}/gifs/*'   #use sub and not ref to avoid circular dependency 
              - Sid: CreateLogGroup
                Action:
                  - logs:CreateLogGroup
                Effect: Allow
                Resource: 
                  - '*'
              - Sid: WriteToLogGroup
                Action: 
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: 
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${PicamLambdaName}-${AWS::Region}'
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${PicamLambdaName}-${AWS::Region}:log-stream:*'
      RoleName: !Sub '${PicamRoleName}-${AWS::Region}'
  PicamLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies: 
        - PolicyName: !Sub '${PicamLambdaRoleName}-${AWS::Region}-permissions'
          PolicyDocument: 
            Version: 2012-10-17
            Statement:
              - Sid: ReadFromGifsFolder
                Action: 's3:GetObject'
                Effect: Allow
                Resource: 
                  - !Sub 'arn:aws:s3:::${PicamBucketName}/gifs/*'   #use sub and not ref to avoid circular dependency 
      RoleName: !Sub '${PicamLambdaRoleName}-${AWS::Region}'
